// API PATH
export const GET_GIFS_TRENDING_PATH = "gifs/trending";

// GET GIFS TRENDING CONSTANTS
export const GET_GIFS_TRENDING_REQUEST = "GET_GIFS_TRENDING_REQUEST";
export const GET_GIFS_TRENDING_SUCCESS = "GET_GIFS_TRENDING_SUCCESS";
export const GET_GIFS_TRENDING_FAILURE = "GET_GIFS_TRENDING_FAILURE";

export const SET_GIFS_TRENDING_ANALYTICS = "SET_GIFS_TRENDING_ANALYTICS";
