// API PATH
export const GET_RANDOMID_PATH = "randomid";

// GET RANDOMID
export const GET_RANDOMID_REQUEST = "GET_RANDOMID_REQUEST";
export const GET_RANDOMID_SUCCESS = "GET_RANDOMID_SUCCESS";
export const GET_RANDOMID_FAILURE = "GET_RANDOMID_FAILURE";

export const SET_NOTIFY_MODAL = "SET_NOTIFY_MODAL";
